"""your message

Revision ID: 127933d6bab9
Revises: b0b1bdfa462a
Create Date: 2024-04-01 21:16:24.352101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127933d6bab9'
down_revision = 'b0b1bdfa462a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
